#!/bin/sh

### BEGIN INIT INFO
# Provides:        mea-edomus
# Required-Start:  $network $syslog
# Required-Stop:   $network $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start mea-edomus daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/data/rec/mea-edomus/0.1alpha2/bin/mea-edomus
PIDFILE=/var/run/mea-edomus.pid
MEAEDOMUS_OPT="--basepath=/data/rec/mea-edomus/0.1alpha2/"
test -x $DAEMON || exit 5

#if [ -r /etc/default/ntp ]; then
#	. /etc/default/ntp
#fi

RUNASUSER=pi
UGID=$(getent passwd $RUNASUSER | cut -f 3,4 -d:) || true

case $1 in
	start)
		log_daemon_msg "Starting mea-edomus" "mea-edomus"
		if [ -z "$UGID" ]; then
			log_failure_msg "user \"$RUNASUSER\" does not exist"
			exit 1
		fi
  		start-stop-daemon --make-pidfile --background --chuid $RUNASUSER --start --pidfile $PIDFILE --startas $DAEMON -- $MEAEDOMUS_OPT
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping mea-edomus" "mea-edomus"
  		start-stop-daemon --stop --signal 3 --quiet --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "mea-edomus"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
