CREATE DATABASE DOMOTIQUE;

CREATE USER edomusdev;
CREATE USER edomusdev@'localhost';

SET PASSWORD FOR edomusdev = PASSWORD('maison');
SET PASSWORD FOR edomusdev@'localhost' = PASSWORD('maison');

GRANT SELECT, INSERT, DELETE, UPDATE, LOCK TABLES ON DOMOTIQUE.* TO 'edomusdev'@'%' WITH GRANT OPTION;
GRANT SELECT, INSERT, DELETE, UPDATE, LOCK TABLES ON DOMOTIQUE.* TO 'edomusdev'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;

USE DOMOTIQUE;


CREATE TABLE IF NOT EXISTS temperatures (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	date DATETIME,
	temp FLOAT,
   id_location TINYINT,
	id_thermometer TINYINT,
	flag TINYINT,
	
	PRIMARY KEY(id)
);

SHOW COLUMNS FROM temperatures;


CREATE TABLE IF NOT EXISTS electricity_counters (
	record_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
   sensor_id TINYINT,
	date DATETIME,
	wh INT UNSIGNED,
	kwh MEDIUMINT UNSIGNED,
	flag TINYINT,
	
	PRIMARY KEY(record_id)
);

SHOW COLUMNS FROM electricity_counters;


CREATE TABLE IF NOT EXISTS pinst (
	record_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
   sensor_id TINYINT,
	date DATETIME,
	power FLOAT,
	delta_t FLOAT,
	flag TINYINT,
	
	PRIMARY KEY(record_id)
);

SHOW COLUMNS FROM pinst;

